#!/bin/bash 

export TMPDIR=/tmp 
mpirun -np 12 --oversubscribe lmp_mpi  -partition 12x1  -log src/polygon/temp/log.lammps_43916  -plog src/polygon/temp/log.lammps_43916  -pscreen src/polygon/temp/screen_43916  -in src/polygon/lammps_util/script/neb_task.lj43916