#!/bin/bash 

export TMPDIR=/tmp 
mpirun -np 36 --oversubscribe lmp_mpi  -partition 36x1  -log src/polygon/temp/log.lammps_3997  -plog src/polygon/temp/log.lammps_3997  -pscreen src/polygon/temp/screen_3997  -in src/polygon/lammps_util/script/neb_task.lj3997