#!/bin/bash 

export TMPDIR=/tmp
mpirun -np 12 --oversubscribe lmp_mpi  -partition 12x1 -log src/polygon/temp/log.lammps -plog src/polygon/temp/log.lammps -pscreen  src/polygon/temp/screen -in src/polygon/lammps_util/script/neb_task.lj

