#!/bin/bash 

export TMPDIR=/tmp 
mpirun -np 36 --oversubscribe lmp_mpi  -partition 36x1  -log src/polygon/temp/log.lammps_4115  -plog src/polygon/temp/log.lammps_4115  -pscreen src/polygon/temp/screen_4115  -in src/polygon/lammps_util/script/neb_task.lj4115