#!/bin/bash 

export TMPDIR=/tmp 
mpirun -np 12 --oversubscribe lmp_mpi  -partition 12x1  -log src/polygon/temp/log.lammps_47178  -plog src/polygon/temp/log.lammps_47178  -pscreen src/polygon/temp/screen_47178  -in src/polygon/lammps_util/script/neb_task.lj47178